### ISSUE TITLE
throw new TypeError('Path must be a string. Received ' +

### ISSUE THREAD

**Issue by rofrol** [rundis/elm-light#29]
Environment:
- Windows10
- Elm 0.17.1 installed with exe in path without spaces
- Light Table 0.8.1
- elm-light 0.4.1

```
#<path.js:8
    throw new TypeError('Path must be a string. Received ' +
    ^

TypeError: Path must be a string. Received null
    at assertPath (path.js:8:11)
    at Object.win32.relative (path.js:257:3)
    at FSWatcher.<anonymous> (C:\Users\frolow\AppData\Roaming\LightTable\plugins\elm_light\node\elm-client.js:209:24)
    at emitThree (events.js:97:13)
    at FSWatcher.emit (events.js:175:7)
    at C:\Users\frolow\AppData\Roaming\LightTable\plugins\elm_light\node_modules\chokidar\lib\nodefs-handler.js:54:5
    at Array.forEach (native)
    at fsWatchBroadcast (C:\Users\frolow\AppData\Roaming\LightTable\plugins\elm_light\node_modules\chokidar\lib\nodefs-handler.js:53:36)
    at FSWatcher.handleEvent (C:\Users\frolow\AppData\Roaming\LightTable\plugins\elm_light\node_modules\chokidar\lib\nodefs-handler.js:26:5)
    at emitTwo (events.js:87:13)
>
```

**Comment by rundis** [comment]
Hopefully fixed in version 0.4.2
Let me know if works better now.
