### ISSUE TITLE
Invalid behavior: :lt.plugins.elm-light/elm-doc-start

### ISSUE THREAD

**Issue by ghost** [rundis/elm-light#37]
On a fresh install of Light Table (0.8.1) when I Toggle docs I get this error in the console... I tried uninstall and reinstall but the same error.

Any ideas?

```
TypeError: Illegal invocation
    at get_elm_version (/home/oluijks/.config/LightTable/plugins/elm_light/elm-light_compiled.js:188:46)
    at valid_project_elm_version (/home/oluijks/.config/LightTable/plugins/elm_light/elm-light_compiled.js:307:159)
    at try_connect (/home/oluijks/.config/LightTable/plugins/elm_light/elm-light_compiled.js:17251:78)
    at find_client (/home/oluijks/.config/LightTable/plugins/elm_light/elm-light_compiled.js:17267:16)
    at lt.plugins.elm_light.clients.get_eval_client.get_eval_client__3 (/home/oluijks/.config/LightTable/plugins/elm_light/elm-light_compiled.js:17310:54)
    at lt.plugins.elm_light.clients.get_eval_client.get_eval_client (/home/oluijks/.config/LightTable/plugins/elm_light/elm-light_compiled.js:17320:27)
    at lt.plugins.elm_light.clients.get_eval_client.get_eval_client__2 (/home/oluijks/.config/LightTable/plugins/elm_light/elm-light_compiled.js:17300:68)
    at lt.plugins.elm_light.clients.get_eval_client.get_eval_client (/home/oluijks/.config/LightTable/plugins/elm_light/elm-light_compiled.js:17318:27)
    at ast_pass_through (/home/oluijks/.config/LightTable/plugins/elm_light/elm-light_compiled.js:19009:159)
    at Function.__BEH__elm_doc_start (/home/oluijks/.config/LightTable/plugins/elm_light/elm-light_compiled.js:19043:47)
```

**Comment by rundis** [comment]
1) Can you run `elm --version` on the command line (this is what the plugin invokes to check which version of Elm you have installed)
2) Is Elm in your PATH ? (the plugin needs the Elm executables to be available in the PATH variable)

**Comment by ghost** [comment]
Yes, all elm executables are in my PATH. 

I manage to fix this by making a symlink to /usr/local/bin/elm. Looks like Light Table does not see the executables when they are in my home directory.

Thanks for the quick response ;-)
